<?php 
	$reportData = $block->getViewReportCollection();
?>

<div class="table-wrapper orders-history">
    <table class="data table table-order-items history" id="my-orders-table" border="1">
        <caption class="table-caption"><?= $block->escapeHtml(__('Report An Error')) ?></caption>
        <tr>
            <th scope="col" class="col id"><?= $block->escapeHtml(__('Customer Firstname')) ?></th>
            <td class="col firstname"><?= $block->escapeHtml($reportData->getCustomerFirstname()) ?></td>
        </tr>
        <tr>
            <th scope="col" class="col lastname"><?= $block->escapeHtml(__('Customer Lastname')) ?></th>
            <td class="col firstname"><?= /* @noEscape */ $block->escapeHtml($reportData->getCustomerLastname()) ?></td>
        </tr>
        <tr>
            <th scope="col" class="col error-description"><?= $block->escapeHtml(__('Error Description')) ?></th>
            <td class="col error-description"><?= /* @noEscape */ $block->escapeHtml($reportData->getErrorDescription()) ?></td>
        </tr>
        <tr>
            <th scope="col" class="col attachment"><?= $block->escapeHtml(__('Attachment')) ?></th>
            <td class="col action">
                <a href="<?= $block->escapeUrl($block->getDownloadUrl($reportData->getReportId())) ?>" class="action view">
                    <span><?= $block->escapeHtml($reportData->getAttachment()) ?></span>
                </a>
            </td>
        </tr>
        <tr>
            <th scope="col" class="col created-at"><?= $block->escapeHtml(__('Created At')) ?></th>
            <td class="col created-at"><?= /* @noEscape */ $block->getFormatedate($reportData->getCreatedAt()) ?></td>
        </tr>        
    </table>
</div>

<div class="actions-toolbar">
    <div class="secondary"><a class="action back" href="<?= $block->escapeUrl($block->getBaseUrl().'customerreport/index/index') ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a></div>
</div>