<?php 
	$customerSession = $block->getCustomerSession();
	$customerId = $customerSession->getCustomerData()->getId();
	$customerData = $block->getCustomerData($customerId);
	$firstName = ($customerData->getFirstname()) ? $customerData->getFirstname() : '';
	$lastName = ($customerData->getLastname()) ? $customerData->getLastname() : '';
	$customerEmail = $customerData->getEmail();
?>

<form class="form-address-edit" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off" novalidate="novalidate" action="<?php echo $block->getBaseUrl().'customerreport/index/save' ?>">
	<fieldset class="fieldset order status" data-hasrequired="* Required Fields">
        <legend class="legend"><span>Report An Error</span></legend><br>
		<div class="field field-name-customer-firstname required">
			<label class="label" for="customer-firstname"><span>Customer Firstname</span></label>
			<div class="control">
				<input type="hidden" id="customer-id" name="customer-id" value="<?php echo $customerId; ?>" title="Customer ID" class="input-text" autocomplete="off">
				<input type="hidden" id="customer-email" name="customer-email" value="<?php echo $customerEmail; ?>" title="Customer Email" class="input-text" autocomplete="off">
			    <input type="text" id="customer-firstname" name="customer-firstname" value="<?php echo $firstName; ?>" title="Customer Firstname" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
			</div>
        </div>
		<div class="field field-name-customer-lastname required">
			<label class="label" for="customer-lastname"><span>Customer Lastname</span></label>
			<div class="control">
				<input type="text" id="customer-lastname" name="customer-lastname" value="<?php echo $lastName; ?>" title="Customer Lastname" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
			</div>
		</div>
		<div class="field field-name-error-description required">
			<label class="label" for="error-description"><span>Error Description</span></label>
			<div class="control">
				<input type="text" id="error-description" name="error-description" value="" title="Error Description" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
			</div>
		</div>
		<div class="field field-name-attachment">
			<label class="label" for="attachment"><span>Attachment</span></label>
			<div class="control">
				<input type="file" id="attachment" name="attachment" value="" title="Attachment" class="input-text" data-validate="{required:false}" autocomplete="off" aria-required="false">
				<p>Allowed Extensions : jpg,pdf,doc,png</p>
			</div>
		</div>                        
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="Submit"><span>Submit</span></button>
        </div>
        <div class="secondary"><a class="action back" href="<?= $block->escapeUrl($block->getBaseUrl().'customerreport/index/index') ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a></div>
    </div>
</form>
<script type="text/javascript">
require([
	'jquery',
	'mage/mage'
], function($){
	var dataForm = $('#form-validate');
	dataForm.mage('validation', {});
});
</script>
