<?php 
	$reportData = $block->getReportCollection();
?>
<section class="admin__page-section">
        <div class="admin__page-section-item">
           <table class="admin__table-secondary order-information-table">
                <tr>
                    <th><?= $block->escapeHtml(__('Customer Firstname')) ?></th>
                    <td><?= /* @noEscape */ $block->escapeHtml($reportData->getCustomerFirstname()) ?></td>
                </tr>
                <tr>
                    <th><?= $block->escapeHtml(__('Customer Lastname')) ?></th>
                    <td><?= /* @noEscape */ $block->escapeHtml($reportData->getCustomerLastname()) ?></td>
                </tr>
                <tr>
                    <th><?= $block->escapeHtml(__('Error Description')) ?></th>
                    <td><?= /* @noEscape */ $block->escapeHtml($reportData->getErrorDescription()) ?></td>
                </tr>
                <tr>
                    <th><?= $block->escapeHtml(__('Attachment')) ?></th>
                    <td><a href="<?php echo $block->getDownloadUrl(); ?>"><?= /* @noEscape */ $block->escapeHtml($reportData->getAttachment()) ?></a></td>
                </tr>
                <tr>
                    <th><?= $block->escapeHtml(__('Created At')) ?></th>
                    <td><?= /* @noEscape */ $block->getFormatedate($reportData->getCreatedAt()) ?></td>
                </tr>
            </table>
        </div>
</section>

